// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zjeekhlurwrxrlktrtty.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpqZWVraGx1cndyeHJsa3RydHR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NDMwMzUsImV4cCI6MjA2NDQxOTAzNX0.jX9iaXYxGSD_91gM3ON3Ywl3GqI5ybaQIgkyNzJF-y8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);